pipeline {
    agent any

    stages {

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('06-CI-CD/app') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('06-CI-CD/app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('06-CI-CD/app') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: '06-CI-CD/app/target/*.jar',
                                 fingerprint: true
            }
        }

        stage('Docker Build') {
    steps {
        dir('06-CI-CD') {
            sh 'docker build -t devops-build-app:1.0 .'
        }
    }
}
    }

    post {
        success {
            echo 'DEVOPS-055 Docker Build completed successfully!'
        }

        failure {
            echo 'DEVOPS-055 Build Pipeline failed!'
        }
    }
}