pipeline {
    agent any
    triggers {
        pollSCM('H/2 * * * *')
    }

    stages {

        stage('Build') {
            steps {
                dir('06-CI-CD/app') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('06-CI-CD/app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('06-CI-CD/app') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: '06-CI-CD/app/target/*.jar',
                                 fingerprint: true
            }
        }

        stage('Docker Build') {
            steps {
                dir('06-CI-CD') {
                     sh 'docker build -t devops-build-app:1.0 .'
                }
             }
        }

       stage('Docker Run') {
    steps {
        sh '''
            docker run -d --name devops-health-check -p 8081:8081 devops-build-app:1.0
            sleep 5
            curl -f http://localhost:8081/health
            docker stop devops-health-check
            docker rm devops-health-check
        '''
    }
}

        stage('Docker Push') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USERNAME',
            passwordVariable: 'DOCKER_PASSWORD'
        )]) {
            sh '''
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                docker tag devops-build-app:1.0 "$DOCKER_USERNAME/devops-build-app:1.0"
                docker push "$DOCKER_USERNAME/devops-build-app:1.0"
                docker logout
            '''
        }
    }
    }
    }

    post {
        success {
            echo 'DEVOPS-055 Docker Build completed successfully!'
        }

        failure {
            echo 'DEVOPS-055 Build Pipeline failed!'
        }
    }
}